services:
  relay:
    build: docker/relay
    restart: always
    ports:
      - "4001:4001"
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
  rooms:
    restart: always
    build:
      context: .
      dockerfile: docker/rooms/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
